---
Name: searchlist
---
SilverStripe\ORM\DataObject:
  extensions:
    - Marcz\Search\Extensions\SearchDataListener
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Marcz\Search\Extensions\SearchContentExtension
Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Search\Extensions\SafeguardMember
Marcz\Search\Config:
  clients:
    - name: 'MySQL'
      write: false
      delete: false
      export: false
      class: 'Marcz\Search\Client\MySQLClient'
